[book]
authors = ["Raven Haunts", "Luiz Borges"]
language = "pt-BR"
multilingual = false
src = "src"
title = "Pathwarden (pt-br)"

[build]
build-dir = "docs/"
create-missing = false

[output.html]
smart-punctuation = true

[output.html.fold]
enable = true

[output.html.search]
enable = true
use-boolean-and = true